---
- name: Post-Reboot Setup
  hosts: localhost
  become: yes

  vars:
    snap_packages:
      - core
      - bashtop
      - nutty
      - krita
      - standard-notes
      - wekan
      - onefetch
      - fast
      - snap-store
      - sublime-text
      - pycharm-community --classic
      - notepadqq
      - bottom
      - mqtt-explorer
      - mosquitto
      - redis
      - mapscii
      - asciiquarium
      - simplenote
      - joplin
      - dbgate
      - alacritty
      - xplr
      - git-delta
    npm_packages:
      - @asyncapi/cli
      - @asyncapi/generator
      - @asyncapi/modelina
      - @asyncapi/parser
      - @mock-to-openapi
      - @ungit
      - vtop
      - gtop
      - create-openapi-repo
    brew_packages:
      - nushell
      - tokei
      - dust
      - gitui
      - eureka
      - brew
      - dua
      - mdcat
      - topgrade
      - procs
      - trippy
      - macchina
      - xplr
    flatpak_apps:
      - org.gaphor.Gaphor
      - dev.lapce.lapce
      - org.wezfurlong.wezterm

  tasks:

    - name: Install Snap packages
      snap:
        name: "{{ item }}"
        state: present
      loop: "{{ snap_packages }}"

    - name: Add Flatpak repository
      shell: |
        flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      args:
        executable: /bin/bash

    - name: Install Flatpak apps
      shell: "flatpak install -y --user flathub {{ item }}"
      loop: "{{ flatpak_apps }}"
      args:
        executable: /bin/bash

    - name: Install NVM
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        nvm install --lts
      args:
        executable: /bin/bash

    - name: Install NPM packages
      shell: "npm install -g {{ item }}"
      loop: "{{ npm_packages }}"

    - name: Install Homebrew
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$($(brew --prefix)/bin/brew shellenv)"' >> ~/.bashrc
      args:
        executable: /bin/bash

    - name: Install Brew packages
      shell: "brew install {{ item }}"
      loop: "{{ brew_packages }}"

    - name: Clone and setup Swagger Editor
      shell: |
        git clone https://github.com/swagger-api/swagger-editor.git ~/swagger-editor
        cd ~/swagger-editor
        npm install
      args:
        executable: /bin/bash

    - name: Install Vacuum via Brew
      shell: |
        brew install daveshanley/vacuum/vacuum
      args:
        executable: /bin/bash
